# Generated by Django 2.1.2 on 2019-06-21 02:39

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conway_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConwayConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('board', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), size=None), size=None)),
                ('conway', models.BooleanField()),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='created')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conway_app.User')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
