# Generated by Django 2.1.2 on 2019-06-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conway_app', '0002_conwayconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conwayconfig',
            name='board',
            field=models.TextField(),
        ),
    ]
