# Generated by Django 2.1.2 on 2019-06-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conway_app', '0003_auto_20190621_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conwayconfig',
            name='owner',
            field=models.TextField(),
        ),
    ]
