# Generated by Django 2.1.2 on 2019-06-21 06:45

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conway_app', '0004_auto_20190621_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conwayconfig',
            name='board',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='conwayconfig',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conway_app.User'),
        ),
    ]
